/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BotConfig {
  'emaScalpingConfig' : [] | [EmaScalpingBotConfig],
  'mode' : BotMode,
  'botType' : BotType,
  'riskManagement' : RiskManagement,
  'macdRsiConfig' : [] | [MacdRsiBotConfig],
  'gridConfig' : [] | [GridBotConfig],
}
export type BotMode = { 'automated' : null } |
  { 'manual' : null };
export type BotType = { 'grid' : null } |
  { 'emaScalping' : null } |
  { 'macdRsi' : null };
export interface EmaScalpingBotConfig {
  'ema9Period' : bigint,
  'takeProfitPercent' : number,
  'ema21Period' : bigint,
  'stopLossPercent' : number,
}
export interface GridBotConfig {
  'investmentPerGrid' : number,
  'lowerBound' : number,
  'upperBound' : number,
  'gridLevels' : bigint,
}
export interface MacdRsiBotConfig {
  'timeframe' : string,
  'leverage' : number,
  'positionSize' : number,
}
export interface OrderRequest {
  'orderType' : string,
  'price' : number,
  'amount' : number,
  'symbol' : string,
}
export interface RiskManagement {
  'maxPositionSize' : number,
  'takeProfitPercent' : number,
  'stopLossPercent' : number,
  'dailyLossLimit' : number,
}
export interface TradeRecord {
  'tradeType' : string,
  'side' : string,
  'botType' : [] | [BotType],
  'tradeId' : string,
  'timestamp' : bigint,
  'price' : number,
  'amount' : number,
  'symbol' : string,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[string], string>,
  'clearUserData' : ActorMethod<[Principal], undefined>,
  'deleteApiCredentials' : ActorMethod<[], undefined>,
  'deleteBotConfig' : ActorMethod<[bigint], undefined>,
  'getAllTradingHistory' : ActorMethod<
    [],
    Array<[Principal, Array<TradeRecord>]>
  >,
  'getAllUserBotConfigs' : ActorMethod<
    [],
    Array<[Principal, Array<BotConfig>]>
  >,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getBalance' : ActorMethod<[], number>,
  'getBotConfigs' : ActorMethod<[], Array<BotConfig>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTradingHistory' : ActorMethod<[], Array<TradeRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTradingHistory' : ActorMethod<[Principal], Array<TradeRecord>>,
  'hasApiCredentials' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[OrderRequest], string>,
  'saveApiCredentials' : ActorMethod<[string, string], undefined>,
  'saveBotConfig' : ActorMethod<[BotConfig], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBotConfig' : ActorMethod<[bigint, BotConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];