/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BotType = IDL.Variant({
  'grid' : IDL.Null,
  'emaScalping' : IDL.Null,
  'macdRsi' : IDL.Null,
});
export const TradeRecord = IDL.Record({
  'tradeType' : IDL.Text,
  'side' : IDL.Text,
  'botType' : IDL.Opt(BotType),
  'tradeId' : IDL.Text,
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
  'amount' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const EmaScalpingBotConfig = IDL.Record({
  'ema9Period' : IDL.Nat,
  'takeProfitPercent' : IDL.Float64,
  'ema21Period' : IDL.Nat,
  'stopLossPercent' : IDL.Float64,
});
export const BotMode = IDL.Variant({
  'automated' : IDL.Null,
  'manual' : IDL.Null,
});
export const RiskManagement = IDL.Record({
  'maxPositionSize' : IDL.Float64,
  'takeProfitPercent' : IDL.Float64,
  'stopLossPercent' : IDL.Float64,
  'dailyLossLimit' : IDL.Float64,
});
export const MacdRsiBotConfig = IDL.Record({
  'timeframe' : IDL.Text,
  'leverage' : IDL.Float64,
  'positionSize' : IDL.Float64,
});
export const GridBotConfig = IDL.Record({
  'investmentPerGrid' : IDL.Float64,
  'lowerBound' : IDL.Float64,
  'upperBound' : IDL.Float64,
  'gridLevels' : IDL.Nat,
});
export const BotConfig = IDL.Record({
  'emaScalpingConfig' : IDL.Opt(EmaScalpingBotConfig),
  'mode' : BotMode,
  'botType' : BotType,
  'riskManagement' : RiskManagement,
  'macdRsiConfig' : IDL.Opt(MacdRsiBotConfig),
  'gridConfig' : IDL.Opt(GridBotConfig),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
  'createdAtNanos' : IDL.Int,
});
export const OrderRequest = IDL.Record({
  'orderType' : IDL.Text,
  'price' : IDL.Float64,
  'amount' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UpdateUserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
  'createdAtNanos' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Text], [IDL.Text], []),
  'clearUserData' : IDL.Func([IDL.Principal], [], []),
  'deleteApiCredentials' : IDL.Func([], [], []),
  'deleteBotConfig' : IDL.Func([IDL.Nat], [], []),
  'getAllTradingHistory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(TradeRecord)))],
      ['query'],
    ),
  'getAllUserBotConfigs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(BotConfig)))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getApiBotStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getBalance' : IDL.Func([], [IDL.Float64], []),
  'getBotConfigs' : IDL.Func([], [IDL.Vec(BotConfig)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTradingHistory' : IDL.Func([], [IDL.Vec(TradeRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTradingHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TradeRecord)],
      ['query'],
    ),
  'hasApiCredentials' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([OrderRequest], [IDL.Text], []),
  'refreshApiCredentialsValidation' : IDL.Func([], [IDL.Bool], []),
  'saveApiCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(BotType)],
      [],
      [],
    ),
  'saveBotConfig' : IDL.Func([BotConfig], [], []),
  'saveCallerUserProfile' : IDL.Func([UpdateUserProfile], [], []),
  'updateApiBotTypes' : IDL.Func([IDL.Vec(BotType)], [], []),
  'updateBotConfig' : IDL.Func([IDL.Nat, BotConfig], [], []),
  'verifyApiCredentials' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BotType = IDL.Variant({
    'grid' : IDL.Null,
    'emaScalping' : IDL.Null,
    'macdRsi' : IDL.Null,
  });
  const TradeRecord = IDL.Record({
    'tradeType' : IDL.Text,
    'side' : IDL.Text,
    'botType' : IDL.Opt(BotType),
    'tradeId' : IDL.Text,
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
    'amount' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const EmaScalpingBotConfig = IDL.Record({
    'ema9Period' : IDL.Nat,
    'takeProfitPercent' : IDL.Float64,
    'ema21Period' : IDL.Nat,
    'stopLossPercent' : IDL.Float64,
  });
  const BotMode = IDL.Variant({ 'automated' : IDL.Null, 'manual' : IDL.Null });
  const RiskManagement = IDL.Record({
    'maxPositionSize' : IDL.Float64,
    'takeProfitPercent' : IDL.Float64,
    'stopLossPercent' : IDL.Float64,
    'dailyLossLimit' : IDL.Float64,
  });
  const MacdRsiBotConfig = IDL.Record({
    'timeframe' : IDL.Text,
    'leverage' : IDL.Float64,
    'positionSize' : IDL.Float64,
  });
  const GridBotConfig = IDL.Record({
    'investmentPerGrid' : IDL.Float64,
    'lowerBound' : IDL.Float64,
    'upperBound' : IDL.Float64,
    'gridLevels' : IDL.Nat,
  });
  const BotConfig = IDL.Record({
    'emaScalpingConfig' : IDL.Opt(EmaScalpingBotConfig),
    'mode' : BotMode,
    'botType' : BotType,
    'riskManagement' : RiskManagement,
    'macdRsiConfig' : IDL.Opt(MacdRsiBotConfig),
    'gridConfig' : IDL.Opt(GridBotConfig),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Text,
    'createdAtNanos' : IDL.Int,
  });
  const OrderRequest = IDL.Record({
    'orderType' : IDL.Text,
    'price' : IDL.Float64,
    'amount' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UpdateUserProfile = IDL.Record({
    'username' : IDL.Text,
    'email' : IDL.Text,
    'createdAtNanos' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Text], [IDL.Text], []),
    'clearUserData' : IDL.Func([IDL.Principal], [], []),
    'deleteApiCredentials' : IDL.Func([], [], []),
    'deleteBotConfig' : IDL.Func([IDL.Nat], [], []),
    'getAllTradingHistory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(TradeRecord)))],
        ['query'],
      ),
    'getAllUserBotConfigs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(BotConfig)))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getApiBotStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getBalance' : IDL.Func([], [IDL.Float64], []),
    'getBotConfigs' : IDL.Func([], [IDL.Vec(BotConfig)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTradingHistory' : IDL.Func([], [IDL.Vec(TradeRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTradingHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TradeRecord)],
        ['query'],
      ),
    'hasApiCredentials' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([OrderRequest], [IDL.Text], []),
    'refreshApiCredentialsValidation' : IDL.Func([], [IDL.Bool], []),
    'saveApiCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(BotType)],
        [],
        [],
      ),
    'saveBotConfig' : IDL.Func([BotConfig], [], []),
    'saveCallerUserProfile' : IDL.Func([UpdateUserProfile], [], []),
    'updateApiBotTypes' : IDL.Func([IDL.Vec(BotType)], [], []),
    'updateBotConfig' : IDL.Func([IDL.Nat, BotConfig], [], []),
    'verifyApiCredentials' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };